### PR TITLE
Enable WATO rule override of state when reboot is required

### PR DESCRIPTION
**Pull request by moschlar**
Hi Henri,

would you mind merging this change and uploading a new version of the mkp?

Regards,
Moritz

### CODE REVIEW

**Comment by moschlar** [comment]
Thanks! Could you also upload it to the Check_MK Exchange at https://mathias-kettner.de/check_mk_exchange_upload.php?HTML=yes ?

**Comment by HenriWahl** [comment]
Yes I did so yesterday.

**Comment by HenriWahl** [comment]
After using your changes I get an UNKOWN error for all hosts which need reboots:
```

Exception | TypeError ('NoneType' object is unsubscriptable)
-- | --
Traceback | File "/omd/sites/monitor/share/check_mk/modules/check_mk_base.py", line 1506, in do_all_checks_on_host     result = sanitize_check_result(check_function(item, params, info), check_uses_snmp(checkname))    File "/omd/sites/monitor/local/share/check_mk/checks/yum", line 73, in check_yum     level = params["reboot_req"]
```
I guess this is not intended? Or is there something I should change in settings?

**Comment by HenriWahl** [comment]
I solved this in https://github.com/HenriWahl/checkmk-agent-plugin-yum/commit/f96cac058276af2c7da0ce4ab7f27550273df6c3
Latest 2.0.7 is uploaded here and to Check_MK Exchange.

**Comment by moschlar** [comment]
Ah thanks!

**Pull request merged**
